[package]
name = "bp-bridge-hub-kusama"
description = "Primitives of BridgeHubKusama parachain runtime."
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

# Bridge Dependencies
bp-bridge-hub-cumulus = { default-features = false , version = "0.4.0" }
bp-runtime = { default-features = false , version = "0.4.0" }
bp-messages = { default-features = false , version = "0.4.0" }

# Substrate Based Dependencies
frame-support = { default-features = false, version = "25.0.0" }
sp-api = { default-features = false, version = "23.0.0" }
sp-runtime = { default-features = false, version = "28.0.0" }
sp-std = { default-features = false , version = "12.0.0" }

[features]
default = [ "std" ]
std = [
	"bp-bridge-hub-cumulus/std",
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
]
