[package]
name = "bp-bridge-hub-kusama"
description = "Primitives of BridgeHubKusama parachain runtime."
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

# Local
kusama-runtime-constants = { path = "../../../../relay/kusama/constants", default-features = false}
polkadot-runtime-constants = { path = "../../../../relay/polkadot/constants", default-features = false}

# Bridge Dependencies
bp-bridge-hub-cumulus = { default-features = false , version = "0.7.0" }
bp-runtime = { default-features = false , version = "0.7.0" }
bp-messages = { default-features = false , version = "0.7.0" }

# Substrate Based Dependencies
frame-support = { default-features = false, version = "28.0.0" }
sp-api = { default-features = false, version = "26.0.0" }
sp-runtime = { default-features = false, version = "31.0.1" }
sp-std = { default-features = false , version = "14.0.0" }

[features]
default = [ "std" ]
std = [
	"bp-bridge-hub-cumulus/std",
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"kusama-runtime-constants/std",
	"polkadot-runtime-constants/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
]
