[package]
name = "penpal-emulated-chain"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Penpal emulated chain used for integration tests"
publish = false

[dependencies]

# Substrate
sp-core = { version = "29.0.0" }
frame-support = { version = "29.0.0" }

# Cumulus
parachains-common = { version = "8.0.0" }
cumulus-primitives-core = { version = "0.8.0" }
emulated-integration-tests-common = { version = "4.0.0" }
penpal-runtime = { version = "0.15.0" }

# Runtimes
kusama-emulated-chain = { path = "../../../relays/kusama" }
polkadot-emulated-chain = { path = "../../../relays/polkadot" }
