[relaychain]
default_image = "parity/polkadot:latest"
default_command = "polkadot"
chain_spec_path = "{{CHAIN_SPEC_PATH}}/kusama.json"
chain = "kusama-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
cumulus_based = true
chain_spec_path = "{{CHAIN_SPEC_PATH}}/asset_hub.json"
chain = "asset-hub-kusama-local"

# run charlie as parachain collator
[[parachains.collators]]
name = "charlie"
validator = true
image = "parity/polkadot-parachain:latest"
command = "polkadot-parachain"
args = ["--force-authoring"]

[[parachains]]
id = 1002
cumulus_based = true
chain_spec_path = "{{CHAIN_SPEC_PATH}}/bridge_hub.json"
chain = "bridge-hub-kusama-local"

# run dave as parachain collator
[[parachains.collators]]
name = "dave"
validator = true
image = "parity/polkadot-parachain:latest"
command = "polkadot-parachain"
args = ["--force-authoring"]

[[parachains]]
id = 1004
cumulus_based = true
chain_spec_path = "{{CHAIN_SPEC_PATH}}/people.json"
chain = "people-kusama-local"

# run dave as parachain collator
[[parachains.collators]]
name = "eve"
validator = true
image = "parity/polkadot-parachain:latest"
command = "polkadot-parachain"
args = ["--force-authoring"]

[[parachains]]
id = 1005
cumulus_based = true
chain_spec_path = "{{CHAIN_SPEC_PATH}}/coretime.json"
chain = "coretime-kusama-local"

# run eve as parachain collator
[[parachains.collators]]
name = "ferdie"
validator = true
image = "parity/polkadot-parachain:latest"
command = "polkadot-parachain"
args = ["--force-authoring"]
