[package]
name = "bridge-hub-polkadot-emulated-chain"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Bridge Hub Polkadot emulated chain used for integration tests"
publish = false

[dependencies]

# Substrate
sp-core = { workspace = true, default-features = true }
frame-support = { workspace = true, default-features = true }

# Bridges
bp-messages = { workspace = true }
xcm = { workspace = true }

# Cumulus
parachains-common = { workspace = true, default-features = true }
bridge-hub-common = { workspace = true, default-features = true }
emulated-integration-tests-common = { workspace = true }

# Runtimes
bridge-hub-polkadot-runtime = { workspace = true }
